In [19]:
import numpy as np

In [20]:
# 1. What is diff b/w numpy Array and list

In [21]:
# Python list =>
# These are slow in speed
# It allows mixed data type
# It is not efficient for memory then an array

# Numpy Array =>
# These are in fast in speed
# It does not allows mixed data type
# It is more efficient for memory

In [22]:
# 2. Create an array and calculate shape, size and dimension of it

In [25]:
a = np.array([1,2,3,4,5,6])

In [26]:
print('Shape : ', a.shape)
print('size : ', a.size)
print('dimension : ', a.ndim)

Shape :  (6,)
size :  6
dimension :  1


In [12]:
# 3. What is zeros, ones, eye, diagonal, linspace, unique explain with the code of example

In [33]:
# Zeros => It creates an array whose all values are zero
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
# Ones => It creates an array whose all values are one
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
# eye => It creates an array whose all diagonal values are one
      # => It creates an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
# digonal => It uses the values in digonale of the square matrix which we give
np.diag([3,5,7])

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

In [46]:
# linspace => It create an numpy array with evenly space values
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [48]:
# Unique =>  it return 3 array
# arr -> return array without duplicates
# return_index -> it returns the unique number's index
# return_counts =>  it give frequency of each unique number

In [49]:
a = np.array([1,2,3,1,2,4,1,5,6,7,8,5,1,2])
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 0,  1,  2,  5,  7,  8,  9, 10]),
 array([4, 3, 1, 1, 2, 1, 1, 1]))

In [13]:
# 4. What is horizontal and vertical stacking explain with example

In [57]:
# horizontal stacking ->  It adds 2 or more numpy array horizontally
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3)
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [58]:
# horizontal stacking ->  It adds 2 or more numpy array Vertically
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3)
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [14]:
# 5. What is view vs copy with example

In [66]:
# View => in this a variable creates a copy of original array
#       -> it takes the reference of it
#       -> if i change in new array then it reflect in original array
a = np.arange(1,11)
print(a)
b = a
b[0] = 10
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[10  2  3  4  5  6  7  8  9 10]


In [70]:
# copy => in this a variable creates a different copy of original array
#       -> it does not takes the of it
#       -> if i change in new array then it does not reflect in original array
a = np.arange(1,11)
print(a)
b = a.copy()
b[0] = 10
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[10  2  3  4  5  6  7  8  9 10]


In [15]:
# 6. You have toh create two matrix of shape 2*2 and perform matrix multiplication

In [73]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(6,10).reshape(2,2)
a.dot(b)

array([[22, 25],
       [50, 57]])

In [16]:
# 7. You have to create an array in range 1 to 10 and then you have to reshape it 3*3 and
# then perform total sum, row sum ,column sum

In [80]:
a = np.arange(1,10).reshape(3,3)
print(a)
print('Total sum : ', np.sum(a))
print('Row sum : ', np.sum(a, axis=1))
print('Column sum : ', np.sum(a, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Total sum :  45
Row sum :  [ 6 15 24]
Column sum :  [12 15 18]


In [17]:
# 8. What is random integer, rand, seed in numpy explain with code

In [83]:
# random integer -> it generates random integers
np.random.randint(1,10, 5)

array([3, 3, 2, 4, 8])

In [86]:
# rand -> it generates random integers b/w 0 to 1
np.random.rand(2,3)

array([[0.68503356, 0.91199553, 0.92123836],
       [0.25335557, 0.50710839, 0.7054736 ]])

In [96]:
# seed => It fixes the random values
np.random.seed(45)
np.random.rand(2,3)

array([[0.98901151, 0.54954473, 0.2814473 ],
       [0.07728957, 0.4444695 , 0.47280797]])