In [2]:
# 1. write statement to import numpy 
import numpy as np 

In [3]:
# 2.
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# 3.
np.random.randint(1,100,10)

array([45, 98, 18, 23, 59, 49,  7, 37, 69, 55], dtype=int32)

In [13]:
# 4.
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# 5.  
a = np.array([5,5,5,5,5,5,5,5,5,5])
a 

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [16]:
# 6.  
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# 7.  
np.random.rand(9).reshape(3,3)  

array([[0.19519518, 0.6473846 , 0.92823015],
       [0.97559784, 0.35197873, 0.39717169],
       [0.81705013, 0.09131463, 0.48554894]])

In [27]:
# 8.  
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(np.hstack((a,b))) 
print()
print(np.vstack((a,b))) 

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
