In [1]:
# Introduction to numpy -----> 
# Numpy -> Num(Numerical) + Py(Python) 

# This is an open-source library of python and this is used for scientific calculation 
# List is hetrogeneous data type and numpy is homogeneous data type 

In [2]:
import numpy as np 

In [3]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
a = np.array([1,2,3])
a*3

array([3, 6, 9])

In [6]:
a = [1,2,3]
b = np.array(a) 
b

array([1, 2, 3])

In [7]:
print(type(a)) 
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print('Total Shape : ',b.shape)      ## shape -> row,column
print('Total Elements : ',b.size)    ## size -> row*column 
print('Total Dimensions : ',b.ndim)  ## total dimension = 2

Total Shape :  (3, 3)
Total Elements :  9
Total Dimensions :  2


### Pre-Built functions of Numpy

In [11]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [13]:
a = np.zeros((3,4))  ## np.zeros(shape)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
a = np.ones(4) 
a

array([1., 1., 1., 1.])

In [15]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a = np.ones((5,6))
print(a)
print('Shape : ', a.shape)
print('dimension : ', a.ndim) 
print('Total elements : ', a.size) 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Shape :  (5, 6)
dimension :  2
Total elements :  30
