In [2]:
import numpy as np 
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
a = np.array([1,45,78,90]) 
print(a)

[ 1 45 78 90]


In [7]:
b = np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [10]:
a = np.random.randint(1,10,3) 
a

array([8, 5, 5], dtype=int32)

In [12]:
a = np.random.rand(5)
a

array([0.26673555, 0.43749281, 0.58830618, 0.03844141, 0.46105724])

In [16]:
np.random.seed(3) 
a = np.random.randint(1,10,3)
a

array([9, 4, 9], dtype=int32)

In [17]:
a = np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [19]:
a[3:6] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [21]:
a = np.array([10,20,30,40,50,60,70,80]) 
b = a[3:6].copy()
b[:]=0

### Operation on array

In [28]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [30]:
b = a%2==0 
a[b]

array([ 2,  4,  6,  8, 10, 12, 14])

In [31]:
a = np.random.randint(1,50,12)
a

array([ 9,  1, 22, 20, 11, 44, 42, 11, 22, 39, 33, 21], dtype=int32)

In [32]:
a.reshape(2,6)

array([[ 9,  1, 22, 20, 11, 44],
       [42, 11, 22, 39, 33, 21]], dtype=int32)

In [33]:
a.reshape(3,4)

array([[ 9,  1, 22, 20],
       [11, 44, 42, 11],
       [22, 39, 33, 21]], dtype=int32)

In [34]:
a = np.arange(1,5).reshape(2,2) 
a

array([[1, 2],
       [3, 4]])

In [35]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [36]:
a+b

array([[ 6,  8],
       [10, 12]])

In [37]:
a-b

array([[-4, -4],
       [-4, -4]])

In [41]:
a*b #not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [42]:
a.dot(b) # matrix multiplication

array([[19, 22],
       [43, 50]])